apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
# The following values are base64-encoded.
# If you'd like to change them, you can encode your own values like this:
# echo -n "<your-value>" | base64
data:
  AWS_ACCESS_KEY_ID: dGVzdC1rZXk= # test-key
  AWS_SECRET_ACCESS_KEY: dGVzdC1zZWNyZXQta2V5 # test-secret-key
  AWS_ENDPOINTS: aHR0cDovLzE3Mi4xNy4wLjE6OTAwMA== # http://172.17.0.1:9000